In [3]:
import numpy as np

**Valid Sudoku**

In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [6]:
np.sum(s , axis=1) # column wise sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [7]:
np.sum(s, axis=0) #row wise sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [20]:
s[0:3 , 0:3]
s[0:3 ,3:6 ]
# 3 x 3 block sum check
for i in range(0,9,3):
    for j in range(0,9 , 3):
        sum = np.sum(s[i:i+3 , j:j+3])
        print(sum)

45
45
45
45
45
45
45
45
45


**General Questions**

In [57]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [23]:
#Get the shape of the matrix.
data.shape


(5, 3)

In [25]:
#Find the average age of students.
print(np.mean(data[: , 0])) # first extract all the rows and then select column slicing

18.4


In [26]:
#Extract Math marks of all students.
print(data[: , 1])

[85 92 76 65 90]


In [27]:
#Find the highest Science mark.
print(data[:,2].max())

95


In [28]:
#Get details of the student who scored more than 90 in Math.
#Here we get details of students also so we use "data[...]" outside bcz we have to extract the data
print(data[data[:,1] > 90])
# so it will print the details of student 2

[[19 92 88]]


In [58]:
#Increase Math marks of all students by 5.
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [40]:
#Find how many students are younger than 19.
print(data[data[:,0] < 19])
len(data[data[:,0] < 19])

[[18 85 78]
 [17 76 95]
 [18 65 70]]


3

In [42]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[: , 1:3] , axis= 0)

array([81.6, 83.2])

In [48]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] > 80) & (data[:,2] > 80)] # make sure to use proper commas

array([[19, 92, 88],
       [20, 90, 85]])

In [53]:
#Replace all Science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
data
#sab sa phle ham na wo columns extract kia phir use column ko select kr ka condition apply ki then usko zero ka equal kr dia 

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

In [ ]:
#<Make sure to run data cell every time you solve a qs for perfect output bcz sometimes data become change>