In [5]:
import numpy as np #we can simply wirte import numpy but then we have to use to word numpy before using any funtion 

In [18]:
arr = np.array([1,2,3,4]) #Must have same datatype (if not, numpy will convert into one single datatype )
# String  >  Float  >  Int
# String is most powerful — converts everything!
# Float beats Int!
print(arr)
arr

[1 2 3 4]


array([1, 2, 3, 4])

In [13]:
list = [1,3,"hello" , False , 3.564] #Can use multiple datatypes 
list

[1, 3, 'hello', False, 3.564]

In [15]:
arr2 = np.array([1,3,"hello" , False , 3.564])
print(arr2)

['1' '3' 'hello' 'False' '3.564']


In [16]:
#We can Create the array from existing list
l = [2,4,6,32,53]
arr3 = np.array(l)
print(type(arr3))
print(arr3)

<class 'numpy.ndarray'>
[ 2  4  6 32 53]


In [24]:
#Note : Alltough Python list support 2D array but its little bit confusing and difficult to perform operation over it 
l1 = [[1,2,4],[2,3,4],[3,6,2]]
print(l1) 
print(type(l1))
#looks fine but in Python we deal matrixes and this doesn't look like matrix and in fact it is very slow and uses loops for every operation. Also it
#is not memory efficient
#And if we print its type is still list, just like simple list

[[1, 2, 4], [2, 3, 4], [3, 6, 2]]
<class 'list'>


In [26]:
#So we use NumPy matrix
mat = np.array(l1)
print(mat)
print(type(mat))
#Now it looks like matrix and it is fast as compare to python list and its type is ndarray. Also on this ndarray indexing is very easy 
# and it is very memory efficent

[[1 2 4]
 [2 3 4]
 [3 6 2]]
<class 'numpy.ndarray'>


In [ ]:
# Tensor = A multi-dimensional array — just a fancy name for arrays with different dimensions!
# 0D  →  Single Number      →  Scalar    →  5
# 1D  →  Single Row         →  Vector    →  [1, 2, 3]
# 2D  →  Rows & Columns     →  Matrix    →  [[1,2],[3,4]]
# 3D+ →  Multiple Matrices  →  Tensor    →  [[[1,2],[3,4]],[[5,6],[7,8]]]

In [ ]:
# 2. WE CAN GENERATE ARRAY USING DIFFERENT FUNCTIONS

In [28]:
# 1. RANGE
arr = np.arange(6) #0-5
arr2 = np.arange(2,8,2) #2-7 with 2 gaps
arr2

array([2, 4, 6])

In [32]:
# 2. ZEROS 
arr = np.zeros(5) # 5 zero in 1D 
arr2 = np.zeros((5,6)) #2D Array (Null Matrix) with 5 rows and 6 columns
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
# 3. Ones
arr = np.ones(5) # 5 zero in 1D 
arr2 = np.ones((5,6)) #2D Array (Matrix) with 5 rows and 6 columns conatining only 1
arr2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [42]:
# 4. linear Space (linspace) - Linspace = Give me N equally spaced numbers between A and B!
arr = np.linspace(1,10,3) # It requires 3 parameters 1. Start 2. End(included) 3. how many numbers u need
# Means output will be from 1 to 10 but every number has spacing of 3 - linear space 
#Above line means 3 equally spaced number b/w 1 and 10

arr2 = np.arange(1,10,3) # It means Give all numbers b/w 1 and 10 in which spacing is 3 --> [1,4,7]
arr

arr3 = np.linspace(0,1,100)
arr3 #100 Numbers and in b/w there is equal spacing -- look how numpy arrays are fast and intelligent

#linspace vs arange
 # arange — you control STEP
    np.arange(0, 10, 2) # [0  2  4  6  8]
 # linspace — you control COUNT
    np.linspace(0, 10, 5) # [0.  2.5  5.  7.5  10.]

In [ ]:
# 3. RANDON NUMBER GENERATOR

In [57]:
arr = np.random.rand()        # single float between 0-1
arr2 = np.random.rand(5)       # 5 floats between 0-1
arr2 # It will print 5 random nos but in b/w 0 and 1 -- Concept of Normalization in Statictics

array([[0.31672856, 0.35514896, 0.03866716, 0.59027623, 0.36459141,
        0.90502035, 0.72594708, 0.56777712],
       [0.87934424, 0.92362215, 0.44027916, 0.43745684, 0.99652631,
        0.06435416, 0.40873718, 0.86584675],
       [0.89265909, 0.56171461, 0.00229735, 0.13786036, 0.58171324,
        0.86377202, 0.68755588, 0.08875097],
       [0.88291631, 0.54298832, 0.55722712, 0.86028995, 0.89265073,
        0.74218685, 0.85555734, 0.53716901],
       [0.46280591, 0.93473142, 0.69744969, 0.39829026, 0.83627809,
        0.02763912, 0.65057632, 0.09269947]])

In [46]:
arr = np.random.randn(5)
arr # It will print 5 random nos but in b/w -3 and 3 -- Concept of Standirization in Statictics

array([ 0.14412932, -0.56800845, -0.45923885, -0.34649424,  2.06608107])

In [101]:
#WHAT IF WE HAVE TO USE RANGE IN FLOATING NOS
arr = np.random.uniform(1.5, 10.5, 5) # 5 Flaoting random nos b/w 1.5 to 10.5
arr

array([9.22932273, 1.58571819, 8.37839783, 6.1029109 , 5.07028387])

In [88]:
arr2 = np.random.randint(low=1,high=10) #Single no b/w 1 and 10 -- low and high are written just to increase readability
arr = np.random.randint(1,100,10) #Generate 10 nos b/w 1 and 100
arr3 = np.random.randint(1, 10, (3,3)) # 3x3 matrix of random numbers
arr

array([ 2, 66, 63,  3, 90, 80, 50, 32, 98, 16], dtype=int32)

In [96]:
values = [1,2,3,5,6,81,3,2,1]
arr = np.random.shuffle(values)
arr
arr2 = np.random.choice(values, 5)
print(type(arr2))
arr2

<class 'numpy.ndarray'>


array([ 1,  3,  3, 81,  2])

In [102]:
# WE CAN ALSO USE A MODERN WAY TO GENERATE RANDOM NUMBERS
rng = np.random.default_rng() #generator or just startup
print(rng.integers(1,100 , 6))
print(rng.random(5)) # generate 5 flaoting numbers b/w 0 and 1
print(rng.uniform(1.5, 10.5, 5))  # for custom float range
values = [1,2,3,5,6,81,3,2,1]
print(rng.choice(values , 5)) # choice 5 nos from list
rng.shuffle(values) #Chnages (Shuffles) the original list
print(values)
print(rng.choice(values , (2,3)))

[39 82 17  1 15 28]
[0.0874173  0.69629687 0.09031285 0.24004679 0.0189621 ]
[2.7655643  9.19448721 7.10170096 2.23583189 6.09317808]
[2 3 6 6 3]
[1, 6, 5, 2, 2, 3, 1, 81, 3]
[[1 6 2]
 [3 3 6]]


In [ ]:
# 4. ARRAY ATTRIBUTES
# Attributes = Properties of an array that give you information ABOUT the array — without doing any operation!
arr.sum()     # Method   — DOES something (adds numbers)
arr.shape     # Attribute — TELLS something (shows shape)
#      👆 no brackets = attribute!

In [103]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)      # (2, 3) tells rows and columns number
print(arr.ndim)       # 2 tells us dimension either 1D or 2D
print(arr.size)       # 6 tells total no of elements inside array
print(arr.dtype)      # int64 tells us the datatype
print(arr.itemsize)   # 8 tells us size of each element in array in bytes
print(arr.nbytes)     # 48 tells us about Total memory used

(2, 3)
2
6
int64
8
48


In [104]:
#5. ARRAY METHODS
# Methods = Actions you perform ON an array — they DO something!

In [121]:
arr = np.array([[1, 2, 3],[4,5,6],[7,8,9]])

print(arr.sum())  #Sum all 
print(arr.mean()) #Find Mean  
print(arr.max())  #Find Max
print(arr.min())  #Find Min 
print(arr.std())  #Find Standard Deviation   
print(arr.var())  #Find Variance
print(arr.prod()) #Find Products of all

#BUT WHAT IF WE WANT SUM OF ROWS OR COLUMNS? and also these above functions are array itself methods not NumPy methods
print(np.sum(arr))
print(np.sum(arr , axis= 1)) #axis 0 -> Column wise and axis 1 -> row wise
print(np.mean(arr)) #Ascending
print(np.sort(arr)[::-1]) #Descending

45
5.0
9
1
2.581988897471611
6.666666666666667
362880
45
[ 6 15 24]
5.0
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [122]:
# 6. RESHAPING AND RESIZING THE ARRAY
# Reshape = Change the shape of array WITHOUT changing data! (does not modifies orignal array, it creates different array with new id)
# Resize  = Change the shape AND can change data too! (modifies orignal array - id remain same before and after modifying)

In [150]:
arr = np.arange(1,31)
# arr.resize(2,2) #Change Original Array
# print(arr)
reshaped_array = arr.reshape(6,5) #Must match with items like 6 * 5 = 30 
reshaped_array #Converted to 2D
flatten_array = reshaped_array.flatten()
flatten_array #Reverse to 1D
array_transpose = reshaped_array.T #Change rows -> column and vice versa
array_transpose


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [133]:
 # -1 in Reshape — Let NumPy calculate:
pythonarr = np.array([1, 2, 3, 4, 5, 6])

arr.reshape(2, -1)   # you say 2 rows — numpy figures out cols
# [[1 2 3]
#  [4 5 6]]          # numpy calculated 3 cols automatically!

arr.reshape(-1, 2)   # you say 2 cols — numpy figures out rows
# [[1 2]
#  [3 4]
#  [5 6]]            # numpy calculated 3 rows automatically!

-1 means "figure it out yourself NumPy!" 🎯

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30]])

In [147]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# flatten — returns COPY
flat = arr.flatten()
flat[0] = 99
print(arr)    # [[1 2 3]   ← original unchanged! ✅
              #  [4 5 6]]

# ravel — returns VIEW
flat = arr.ravel()
flat[0] = 99
print(arr)    # [[99 2 3]  ← original CHANGED! ⚠️
              #  [ 4 5 6]]

[[1 2 3]
 [4 5 6]]
[[99  2  3]
 [ 4  5  6]]
