In [1]:
import numpy as np

In [15]:
arr = np.arange(1,31)
arr.resize(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
slice  = arr[3:,3:]
slice



array([[19, 20],
       [24, 25],
       [29, 30]])

In [38]:
# ARRAY BOOLEAN INDEXING
# Boolean indexing means using True/False conditions to filter or select elements from an array.
# NumPy checks each element → makes a True/False array → returns only True positions

In [34]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
bool_values = arr > 10
bool_values

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [36]:
arr = arr[bool_values] # reassignment
arr
# We can do it in one line 
# arr = arr[arr > 10]
# arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
a = np.array([10, 20, 30, 40, 50])

# AND — both conditions must be True
a[(a > 15) & (a < 45)]    # [20 30 40]

# OR — either condition is True
a[(a < 15) | (a > 45)]    # [10 50]

# NOT — inverts the condition
a[~(a > 25)]              # [10 20]  (same as a <= 25)

array([10, 20])

In [3]:
arr1 = np.array([1,2,3,4])
print(arr1)
arr2 = np.array([4,5,6,7])
print(arr2)

[1 2 3 4]
[4 5 6 7]


In [10]:
print(arr1 * arr2)

[ 4 10 18 28]


In [20]:
arr1 = np.array([1,2,3,4])
arr3 = np.array([[1] , [2] , [6] , [9]])
''' Output of above matrix
[[1]
 [2]
 [6]
 [9]]
'''
print(arr3)
print(arr3 + arr1)
'''

'''

[[1]
 [2]
 [6]
 [9]]
[[ 2  3  4  5]
 [ 3  4  5  6]
 [ 7  8  9 10]
 [10 11 12 13]]


In [24]:
import numpy as np

# Valid examples
A = np.ones((8, 4, 6))
B = np.ones((1, 1, 6))
print((A + B).shape)   # (8, 4, 6) ✓

A = np.ones((8, 4, 6))
B = np.ones((8, 1, 6))
print((A + B).shape)   # (8, 4, 6) ✓

A = np.ones((4, 3))
B = np.ones((1, 3))
print((A + B).shape)   # (4, 3) ✓

A = np.ones((3, 1))
B = np.ones((1, 4))
print((A + B).shape)   # (3, 4) ✓

# Invalid examples — ye sab ValueError denge
try:
    A = np.ones((8, 4, 6))
    B = np.ones((7, 1, 6))
    print((A + B).shape)
except ValueError as e:
    print("Error:", e)   # Error ✗

try:
    A = np.ones((4, 3))
    B = np.ones((4,))
    print((A + B).shape)
except ValueError as e:
    print("Error:", e)   # Error ✗

try:
    A = np.ones((8, 1, 6))
    B = np.ones((7, 1, 5))
    print((A + B).shape)
except ValueError as e:
    print("Error:", e)   # Error ✗

(8, 4, 6)
(8, 4, 6)
(4, 3)
(3, 4)
Error: operands could not be broadcast together with shapes (8,4,6) (7,1,6) 
Error: operands could not be broadcast together with shapes (4,3) (4,) 
Error: operands could not be broadcast together with shapes (8,1,6) (7,1,5) 
