In [1]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [3]:
arr = np.arange(1,6)
arr2 = np.arange(6,11)


array([ 7,  9, 11, 13, 15])

In [12]:
#1. Addition
arr + arr2
#2. Subtraction
arr - arr2
#3. Division
arr / arr2
#4. Multiplication
arr * arr2
#5. Power and Base
arr ** arr2
#6. Modulo
arr % arr2
#7. Floor Division (Floor Function)
arr // arr2
#8. XOR
arr ^ arr2

array([ 7,  5, 11, 13, 15])

In [17]:
#Now if i have to add a scalar number to the each elemeent of list, i have to run 
# loop and add that number to the each element
l = [1,2,3,4,6]
arr = np.array(l)
# l + 10 --> we can not do this. Only way is to do that is using loop

In [19]:
#Now I do not want to run loop over it so numpy will do it automaticallyabs
# l + 10 --> Is Error bcz l is list
arr + 10 #--> works bcz arr is numpy array

array([11, 12, 13, 14, 16])

In [27]:
# DEEP and SHALLOW COPY
# 1. SHALLOW COPY
# A shallow copy creates a new array object but does not create new data in memory  
# it still points to the same data as the original. So if you change the data, 
# the original gets affected too.

A = np.arange(1,10)
B = A.view()
B[0] = 15
print(A)
print(B)

# View creates a new array object but shares the underlying data buffer. So:
# Data changes → affect both
# Shape/dtype changes → independent

# 2. DEEP COPY
# A deep copy creates a new array object AND new data in memory  
# completely independent from the original. Changing it will never affect the original.

X = np.arange(11, 21)
Y = X.copy()
Y[0] = 55
print(X)
print(Y)

[15  2  3  4  5  6  7  8  9]
[15  2  3  4  5  6  7  8  9]
[11 12 13 14 15 16 17 18 19 20]
[55 12 13 14 15 16 17 18 19 20]


In [40]:
# MATRIX MULTIPLICATION
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[7,8] , [3,4]])
print(mat1 * mat2 , end="\n\n") # it is just index multiplication
print(mat1 @ mat2 , end="\n\n") # it is matrix multplication
# We can also use dot function 
print(np.dot(mat1, mat2))

[[ 7 16]
 [ 9 16]]

[[13 16]
 [33 40]]

[[13 16]
 [33 40]]


In [54]:
#STACKING Of ARRAY  
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,8,9])
print(np.vstack((arr , arr2))) # join vertically
print(np.hstack((arr , arr2))) # join horizontally
print(np.column_stack((arr, arr2))) #join vertically and convert into 2D matrix
print(np.stack((arr , arr2) , axis=0)) # 0 for column -- same as vstack
print(np.stack((arr , arr2) , axis=1)) # 1 for row -- same as column stack

[[1 2 3 4]
 [5 6 8 9]]
[1 2 3 4 5 6 8 9]
[[1 5]
 [2 6]
 [3 8]
 [4 9]]
[[1 2 3 4]
 [5 6 8 9]]
[[1 5]
 [2 6]
 [3 8]
 [4 9]]


In [55]:
# On 2D Arrays
mat1 = np.array([[1,2] , [2,3] , [3,4]])
# Actually look like this
# [[1 2]
#  [2 3]
#  [3 4]]
mat2 = np.array([[2,3] , [4,5] , [9,0]])
print(np.vstack((mat1 , mat2)))
print(np.hstack((mat1 , mat2)))
print(np.column_stack((mat1 , mat2)))

[[1 2]
 [2 3]
 [3 4]
 [2 3]
 [4 5]
 [9 0]]
[[1 2 2 3]
 [2 3 4 5]
 [3 4 9 0]]
[[1 2 2 3]
 [2 3 4 5]
 [3 4 9 0]]
